version: '3'

services:
  dynamic_demand:
    image: chartmuseum/chartmuseum:${tag}
    environment:
      - STORAGE_AMAZON_BUCKET=${chart_museum_s3_bucket}
      - STORAGE_AMAZON_REGION=${chart_museum_s3_bucket_region}
      - STORAGE_AMAZON_PREFIX=""
      - STORAGE=amazon
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SESSION_TOKEN
      - AWS_SECRET_ACCESS_KEY
    ports:
      - "${port}:8080"